package com.sw.banca.misc.enums;

public enum ServerResponse {
    OPERATION_SUCCESSFUL,
    INSUFFICIENT_FUNDS,
    CLIENT_NOT_FOUND,
    CLIENT_ALREADY_TRACKED,
    CLIENT_NOT_TRACKED,
    ACCOUNT_NOT_EMPTY,
    CLIENT_ALREADY_EXISTS,
    UNEXPECTED_ERROR
}
